# Generated by Django 5.0.1 on 2024-01-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MyModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("my_tri_state_field1", models.BooleanField(blank=True, null=True)),
                ("my_tri_state_field2", models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
